# https://python-poetry.org/docs/

[tool.poetry]
name = "todo-bot"
version = "2.0.7"
description = "TODO"
authors = []


[tool.poetry.dependencies]
python = ">=3.8,<3.11"

pybotx-smart-logger = "~0.10.1"
pybotx = "0.55.2"
pybotx-fsm = "~0.4.2"

fastapi = "0.95.2"
uvicorn = { version = "~0.17.5", extras = ["standart"] }

aioredis = "~1.3.1"  # TODO: Migrate to 2.0
loguru = ">=0.6.0,<0.7.0"
mako = "~1.2.2"
pydantic = { version = "~1.10.5", extras = ["dotenv"] }

alembic = "~1.13.0"
SQLAlchemy = "~1.4.31"
asyncpg = "0.26.0"  # DB backend for application
psycopg2-binary = "~2.9.2"  # DB backend for alembic (migration tool)
importlib-resources = { version = "^5.4.0", python = "<3.9" }
zipp = { version = "^3.7.0", python = "<3.9" }
importlib-metadata = { version = "^4.11.0", python = "<3.9" }

[tool.poetry.dev-dependencies]
add-trailing-comma = "2.2.1"
autoflake = "1.4.0"
black = "22.3.0"
isort = "5.10.1"
mypy = "0.931.0"
wemake-python-styleguide = "0.16.0"

flake8-bandit = "2.1.2"  # https://github.com/PyCQA/bandit/issues/837
bandit = "1.7.2"  # https://github.com/PyCQA/bandit/issues/837

pytest = "~7.2.1"
pytest-asyncio = "~0.18.2"
pytest-cov = "~3.0.0"

asgi-lifespan = "~1.0.1"
requests = "~2.31.0"
respx = "~0.19.2"

markdown = "3.3.6"  # https://github.com/python-poetry/poetry/issues/4777

[build-system]
requires = ["poetry>=1.1.12"]
build-backend = "poetry.masonry.api"
