name: Lint
on: push
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ExpressApp/github-actions-poetry@v0.1
        with:
          python-version: "3.8.12"
          poetry-version: "1.1.12"

      - name: Run lint
        run: |
          source .venv/bin/activate
          ./scripts/lint
